version: "3"
services:
  db:
    image: postgres:12.2-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_DB
    ports:
      - "$DATABASE_PORT:$DATABASE_PORT"
    volumes:
      - db-data-volume:/var/lib/postgresql/data
      - ./infra/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER:$RABBITMQ_USER
      - RABBITMQ_DEFAULT_PASS:$RABBITMQ_PASSWORD
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data-volume:/var/lib/rabbitmq/
      - rabbitmq-log-volume:/var/log/rabbitmq/

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379

volumes:
  db-data-volume:
  rabbitmq-data-volume:
  rabbitmq-log-volume:
