apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: not-so-smart-cal
build:
  artifacts:
    - image: calendar
      context: calendar
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
portForward:
  - resourceType: service
    resourceName: calendar
    port: 50051
  - resourceType: service
    resourceName: frontend
    port: 3000
