apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: not-so-smart-cal
build:
  artifacts:
    - image: calendar
      context: calendar
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
    - image: graphql
      context: graphql
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.ts"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-dev/*
      - ./infra/k8s/*
portForward:
  - resourceType: service
    resourceName: frontend
    port: 3000
  - resourceType: service
    resourceName: graphql
    port: 4000
  - resourceType: service
    resourceName: calendar-postgres
    port: 5432
    localPort: 54321
