apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
  labels:
    app: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
        - name: calendar
          image: calendar
          env:
            - name: POSTGRES_HOST
              value: minikube-host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: calendar-postgres-credentials
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calendar-postgres-credentials
                  key: password
            - name: AMQP_HOST
              value: minikube-host
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: user
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: password
          envFrom:
            - configMapRef:
                name: calendar-postgres-configuration
            - configMapRef:
                name: rabbitmq-configuration
---
apiVersion: v1
kind: Service
metadata:
  name: calendar
  labels:
    app: calendar
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: calendar
