apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
  labels:
    app: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
        - name: calendar
          image: calendar
---
apiVersion: v1
kind: Service
metadata:
  name: calendar
  labels:
    app: calendar
spec:
  ports:
    - port: 5000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: calendar
