apiVersion: v1
kind: Service
metadata:
  name: graphql
  labels:
    app: graphql
spec:
  ports:
    - port: 4000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: graphql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  labels:
    app: graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: graphql
          image: graphql
          env:
            - name: PORT
              value: "4000"
